name: graph_single_task_tpm_clinical
n_gpu: 1
pin_memory: true
mode: multi cross validation bootstrap

log_directory: Logs/Trainer/
checkpoint_directory: Checkpoints/Trainer/

models:
  Feature_Extractor:
    type: Graph_And_Clinical_Feature_Extractor
    args:
      graph_input_dim: 1
      graph_hidden_dim: 1
      graph_output_dim: 1
      n_genes: 20
      clinical_numerical_dim: 3
      clinical_categorical_dim: 11
      genomic_embedding_dim: 8
      clinical_embedding_dim: 8
  Label_Classifier:
    type: Classifier
    args:
      genomic_embedding_dim: 8
      clinical_embedding_dim: 8
      output_dim: 1

datasets:
  TCGA-READ:
    type: TCGA_Project_Dataset
    args:
      project_id: TCGA-READ
      chosen_features:
        gene_ids: ['APC', 'TP53', 'LRP1B', 'KRAS', 'SMAD4', 'TCF7L2', 'FBXW7', 'ATRX', 'ERBB4','PTEN', 'ATM', 'SETD2', 'NRAS', 'FAT4', 'ARID1A', 'KDR', 'AMER1', 'CREBBP', 'MYH11', 'NBEA']
        clinical_numerical_ids: ['age_at_diagnosis', 'year_of_diagnosis', 'year_of_birth']
        clinical_categorical_ids:
          - gender
          - race
          - ethnicity
      data_directory: Data/TCGA-BRCA/
      cache_directory: Cache/TCGA-BRCA/
      target_type: overall_survival
      genomic_type: tpm
      n_threads: 16
      graph_dataset: True
  # TCGA-LUAD:
  #   type: TCGA_Project_Dataset
  #   args:
  #     project_id: TCGA-LUAD
  #     chosen_features:
  #       gene_ids: ['HNRNPU', 'STAU1', 'KDM1A', 'SERBP1', 'DHX9', 'EMC1', 'SSR1', 'PUM1', 'CLTC', 'PRKRA', 'KRR1', 'OCIAD1', 'CDC73', 'SLC2A1', 'HIF1A', 'PKM', 'CADM1', 'EPCAM', 'ALCAM', 'PTK7']
  #       clinical_numerical_ids: ['age_at_diagnosis', 'year_of_diagnosis', 'year_of_birth']
  #       clinical_categorical_ids:
  #         - gender
  #         - race
  #         - ethnicity
  #     data_directory: Data/TCGA-LUAD/
  #     cache_directory: Cache/TCGA-LUAD/
  #     target_type: overall_survival
  #     genomic_type: tpm
  #     n_threads: 16
  #     graph_dataset: True
  # TCGA-COAD:
  #   type: TCGA_Project_Dataset
  #   args:
  #     project_id: TCGA-COAD
  #     chosen_features:
  #       gene_ids: ['HNRNPL', 'HNRNPU', 'HNRNPA1', 'ZBTB2', 'SERBP1', 'RPL4', 'HNRNPK', 'HNRNPR', 'TFCP2', 'DHX9', 'RNF4', 'PUM1', 'ABCC1', 'CD44', 'ALCAM', 'ABCG2', 'ALDH1A1', 'ABCB1', 'EPCAM', 'PROM1']
  #       clinical_numerical_ids: ['age_at_diagnosis', 'year_of_diagnosis', 'year_of_birth']
  #       clinical_categorical_ids:
  #         - gender
  #         - race
  #         - ethnicity
  #     data_directory: Data/TCGA-COAD/
  #     cache_directory: Cache/TCGA-COAD/
  #     target_type: overall_survival
  #     genomic_type: tpm
  #     n_threads: 16
  #     graph_dataset: True

datasets_manager:
  type: TCGA_Datasets_Manager
  TCGA-READ:
    train: true
    batch_size: 128
    num_folds: 4
    test_split: 0.2
    num_workers: 4
  # TCGA-LUAD:
  #   train: true
  #   batch_size: 128
  #   num_folds: 4
  #   test_split: 0.2
  #   num_workers: 4
  # TCGA-COAD:
  #   train: true
  #   batch_size: 128
  #   num_folds: 4
  #   test_split: 0.2
  #   num_workers: 4

optimizers:
  Feature_Extractor:
    type: SGD
    models:
      - Feature_Extractor
    args:
      lr: 0.01
      momentum: 0.9
  Label_Classifier:
    type: SGD
    models:
      - Label_Classifier
    args:
      lr: 0.01
      momentum: 0.9

lr_schedulers: {}

losses:
  bce_with_logits_loss:
    type: bce_with_logits_loss
    args: {}

metrics:
  - AUROC
  - AUPRC
  - c_index
  - recall
  - precision

plots: {}

runner:
  type: DNN_Trainer
  epochs: 50
  log_epoch: 10
  tensorboard: false
