name: pretrain_graph_brca_tpm
n_gpu: 1
pin_memory: true
mode: multi cross validation bootstrap

log_directory: Logs/Trainer/
checkpoint_directory: Checkpoints/Trainer/

models:
  Feature_Extractor:
    type: Graph_And_Clinical_Feature_Extractor
    args:
      graph_input_dim: 1
      graph_hidden_dim: 4
      graph_output_dim: 2
      n_genes: 20
      clinical_numerical_dim: 3
      clinical_categorical_dim: 11
      genomic_embedding_dim: 8
      clinical_embedding_dim: 0
  Label_Classifier:
    type: Classifier
    args:
      genomic_embedding_dim: 8
      clinical_embedding_dim: 8
      output_dim: 1
      skip: True

datasets:
  TCGA-BRCA:
    type: TCGA_Project_Dataset
    args:
      project_id: TCGA-BRCA
      chosen_features:
        gene_ids: ['ESR1', 'EFTUD2', 'HSPA8', 'STAU1', 'SHMT2', 'ACTB', 'GSK3B', 'YWHAB', 'UBXN6', 'PRKRA', 'BTRC', 'DDX23', 'SSR1', 'TUBA1C', 'SNIP1', 'SRSF5', 'ERBB2', 'MKI67', 'PGR', 'PLAU']
        clinical_numerical_ids: ['age_at_diagnosis', 'year_of_diagnosis', 'year_of_birth']
        clinical_categorical_ids:
          - gender
          - race
          - ethnicity
      data_directory: Data/TCGA-BRCA/
      cache_directory: Cache/TCGA-BRCA/
      target_type: overall_survival
      genomic_type: tpm
      n_threads: 16
      graph_dataset: True

datasets_manager:
  type: TCGA_Datasets_Manager
  TCGA-BRCA:
    train: true
    batch_size: 16
    num_folds: 4
    test_split: 0.2
    num_workers: 4

optimizers:
  Feature_Extractor:
    type: AdamW
    models:
      - Feature_Extractor
    args:
      lr: 0.001
  Label_Classifier:
    type: SGD
    models:
      - Label_Classifier
    args:
      lr: 0.01
      momentum: 0.9

lr_schedulers: {}

losses:
  bce_with_logits_loss:
    type: bce_with_logits_loss
    args: {}

metrics:
  - AUROC
  - AUPRC
  - c_index
  - recall
  - precision

plots: {}

runner:
  type: DNN_Trainer
  epochs: 50
  log_epoch: 10
  tensorboard: False
